-- Run this SQL script in your Supabase SQL Editor

-- 1. Create the services table if it doesn't already exist
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id UUID REFERENCES auth.users(id) NOT NULL,
    service_name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    available_date DATE NOT NULL,
    available_time TIME NOT NULL,
    duration TEXT NOT NULL,
    location TEXT NOT NULL,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Turn on Row Level Security for services
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Policies for services
DROP POLICY IF EXISTS "Providers can insert their own services" ON public.services;
CREATE POLICY "Providers can insert their own services" ON public.services FOR INSERT WITH CHECK (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Providers can update their own services" ON public.services;
CREATE POLICY "Providers can update their own services" ON public.services FOR UPDATE USING (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Providers can delete their own services" ON public.services;
CREATE POLICY "Providers can delete their own services" ON public.services FOR DELETE USING (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Anyone can view services" ON public.services;
CREATE POLICY "Anyone can view services" ON public.services FOR SELECT USING (true);


-- 2. Create the profiles table for Provider details
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    full_name TEXT,
    phone_number TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Turn on Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 3. Trigger to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check if trigger exists before creating it (Postgres 13+ or wrap in DO block for older versions)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'on_auth_user_created') THEN
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
  END IF;
END
$$;

-- 4. Create the bookings table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT REFERENCES public.services(id) NOT NULL,
    customer_id UUID REFERENCES auth.users(id) NOT NULL,
    provider_id UUID REFERENCES auth.users(id) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed', 'cancelled')),
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Turn on Row Level Security for bookings
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Policies for bookings
DROP POLICY IF EXISTS "Customers can insert their own bookings" ON public.bookings;
CREATE POLICY "Customers can insert their own bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Customers can view their own bookings" ON public.bookings;
CREATE POLICY "Customers can view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Customers can update their own bookings" ON public.bookings;
CREATE POLICY "Customers can update their own bookings" ON public.bookings FOR UPDATE USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Providers can view bookings for their services" ON public.bookings;
CREATE POLICY "Providers can view bookings for their services" ON public.bookings FOR SELECT USING (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Providers can update bookings for their services" ON public.bookings;
CREATE POLICY "Providers can update bookings for their services" ON public.bookings FOR UPDATE USING (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Admins can view all bookings" ON public.bookings;
CREATE POLICY "Admins can view all bookings" ON public.bookings FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 5. Create the reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES public.bookings(id) NOT NULL UNIQUE,
    service_id BIGINT REFERENCES public.services(id) NOT NULL,
    customer_id UUID REFERENCES auth.users(id) NOT NULL,
    provider_id UUID REFERENCES auth.users(id) NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Turn on Row Level Security for reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies for reviews
DROP POLICY IF EXISTS "Customers can insert their own reviews" ON public.reviews;
CREATE POLICY "Customers can insert their own reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Customers can view their own reviews" ON public.reviews;
CREATE POLICY "Customers can view their own reviews" ON public.reviews FOR SELECT USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Providers can view reviews for their services" ON public.reviews;
CREATE POLICY "Providers can view reviews for their services" ON public.reviews FOR SELECT USING (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Admins can view all reviews" ON public.reviews;
CREATE POLICY "Admins can view all reviews" ON public.reviews FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);
